name: guia_moteis
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  http: ^1.3.0
  toggle_switch: ^2.3.0
  cached_network_image: ^3.4.1
  brasil_fields: ^1.17.0
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  faker: ^2.2.0
  mocktail: ^1.0.4
  

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
